### ISSUE TITLE
API call failed 

### ISSUE THREAD

**Issue by isuruhera** [Gimly/NetCoreAngularAzureB2CMsal#12]
![image](https://user-images.githubusercontent.com/6005779/32637446-b6bb52f4-c61e-11e7-9097-38eaa8a4d05c.png)

**Comment by Gimly** [comment]
Looking at the error message it looks like you haven't configured the application correctly on Azure AD B2C. How did you create the application in your AD B2C tenant?

**Comment by spottedmahn** [comment]
I had the [same problem once](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/4#issuecomment-314881088)... I was requesting the scope name and I was supposed to be requesting the **scope value**.

**Comment by Gimly** [comment]
Hi, I'm considering this issue close since it was probably a configuration issue. Feel free to reopen if you think it hasn't been fixed.
